# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddace9656ef18cbd62d906a3705a77cb1fa612427be09957b5ec5911f7fc1ac28e8aa8ce4c3acdd811dc2274acfb4ba6b2e4835787494bc97d6dfe52092475a0

test:
  secret_key_base: 0e58d0e0f5760d3f24116fdf167ad44cbe8a1e4336fd4613aa1ab1929e1884e46b429f1e38485a4cfa0edbd4ded2d4413877e92b217b416066174e6f20a0596a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
